const expiredJobsData = [
  {
    id: 1,
    jobTitile: "Property Manager",
    date: "Apr 1, 2022 - May 1, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 2,
    jobTitile: "Assistant Property Manager",
    date: "Aug 16, 2022 - Sep 15, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 3,
    jobTitile: "Development Manager",
    date: "Apr 1, 2022 - May 1, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 4,
    jobTitile: "Junior developer",
    date: "Aug 16, 2022 - Sep 15, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 5,
    jobTitile: "Senior developer",
    date: "Apr 1, 2022 - May 1, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 6,
    jobTitile: "Supervisor",
    date: "Aug 16, 2022 - Sep 15, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 7,
    jobTitile: "Bussiness Analyst",
    date: "Apr 1, 2022 - May 1, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 8,
    jobTitile: "Assistant Property Manager",
    date: "Aug 16, 2022 - Sep 15, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
  {
    id: 9,
    jobTitile: "Watchmen",
    date: "Apr 1, 2022 - May 1, 2022",
    location: "Durham, North Carolina",
    owner: "Ana tenorio",
    hiringManager: "Ana tenorio",
    applicants: "14 Applicants",
    strongFits: 0,
    fits: 1,
    weakFits: 10,
    distortions: 3,
    IncompleteApplications: 5,
    edit: "edit",
    rePost: "Re-post this job",
    jobDesc: "job description",
  },
];

export default expiredJobsData;
